[versions]
gradle-starter = "0.69.0"
maven-kotlin-serialization = "1.6.2"
maven-kotlin = "1.9.22"
maven-junit = "5.10.1"
maven-junit4 = "4.13.2"
maven-assertj = "3.25.2"
activity-compose = "1.8.2"
androidx-compose-compiler = "1.5.8"
androidx-core = "1.12.0"
androidx-test-ext-junit = "1.1.5"
com-squareup-moshi = "1.15.1"
compose-bom = "2024.01.00"
core-ktx = "1.12.0"
espresso-core = "3.5.1"
lifecycle-runtime-ktx = "2.7.0"

[libraries]
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "maven-junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "maven-junit" }
junit-vintage-engine = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "maven-junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
junit4 = { module = "junit:junit", version.ref = "maven-junit4" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "maven-assertj" }

kotlinx-serialization-json-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "maven-kotlin-serialization" }
kotlinx-serialization-json-okio = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json-okio", version.ref = "maven-kotlin-serialization" }
com-squareup-okio = "com.squareup.okio:okio:3.7.0"

activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
org-jetbrains-kotlin-kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "maven-kotlin" }
androidx-lifecycle-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle-runtime-ktx" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext-junit" }
androidx-test-core = "androidx.test:core-ktx:1.5.0"
org-robolectric-core = "org.robolectric:robolectric:4.11.1"
com-squareup-moshi = { module = "com.squareup.moshi:moshi", version.ref = "com-squareup-moshi" }
com-squareup-moshi-moshi-kotlin-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "com-squareup-moshi" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
androidx-compose-animation = { module = "androidx.compose.animation:animation" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-compose-foundation-foundation-layout = { module = "androidx.compose.foundation:foundation-layout" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-material-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-runtime-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata" }
androidx-compose-ui-ui-text = { module = "androidx.compose.ui:ui-text" }
androidx-core-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
org-jetbrains-kotlinx-kotlinx-coroutines-test = "org.jetbrains.kotlinx:kotlinx-coroutines-test:1.7.3"
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
material3 = { module = "androidx.compose.material3:material3" }
ui = { module = "androidx.compose.ui:ui" }
ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
io-nlopez-compose = "io.nlopez.compose.rules:ktlint:0.3.11"

[plugins]
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "maven-kotlin" }
starter-config = { id = "com.starter.config", version.ref = "gradle-starter" }
starter-versioning = { id = "com.starter.versioning", version.ref = "gradle-starter" }
starter-library-kotlin = { id = "com.starter.library.kotlin", version.ref = "gradle-starter" }
starter-library-android = { id = "com.starter.library.android", version.ref = "gradle-starter" }
starter-application-android = { id = "com.starter.application.android", version.ref = "gradle-starter" }
app-cash-licensee = "app.cash.licensee:1.9.0"
starter-easylauncher = "com.starter.easylauncher:6.2.0"
